{% set name = "readthedocs-sphinx-ext" %}
{% set version = "2.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/readthedocs-sphinx-ext-{{ version }}.tar.gz
  sha256: ee5fd5b99db9f0c180b2396cbce528aa36671951b9526bb0272dbfce5517bd27

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests
    - jinja2 >=2.9
    - packaging

test:
  imports:
    - readthedocs_ext
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/readthedocs/readthedocs-sphinx-ext
  summary: Sphinx extension for Read the Docs overrides
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
